version: '3'

services:

  fastapi:
    image: find_path:v8
    ports:
      - "8000:8000"

  django:
    image: planner_web:v3
    ports:
      - "8080:8080"
    volumes:
      - web_data:/app

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - web_data:/app
    depends_on:
      - fastapi
      - django

volumes:
  web_data:
