# Generated by Django 4.2.1 on 2023-05-13 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PathJsonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(db_column='path_data')),
                ('path_type', models.CharField(blank=True, db_column='path_type', db_index=True, max_length=50, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Path JSON Data',
                'verbose_name_plural': 'Path JSON Data',
                'db_table': 'path_json_data',
            },
        ),
    ]
