# Generated by Django 4.2.1 on 2023-05-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_pathjsondata_path_name_pathjsondata_path_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathjsondata',
            old_name='data',
            new_name='path_data',
        ),
        migrations.RenameField(
            model_name='pathjsondata',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='pathjsondata',
            name='end_lat',
            field=models.DecimalField(db_column='end_lat', decimal_places=6, default=None, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pathjsondata',
            name='end_lon',
            field=models.DecimalField(db_column='end_lon', decimal_places=6, default=None, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pathjsondata',
            name='start_lat',
            field=models.DecimalField(db_column='start_lat', decimal_places=6, default=None, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pathjsondata',
            name='start_lon',
            field=models.DecimalField(db_column='start_lon', decimal_places=6, default=None, max_digits=9),
            preserve_default=False,
        ),
    ]
